### ISSUE TITLE
phy_mode object not available in micropython for pico w boards

### ISSUE THREAD

**Issue by sivansh11** [rbenrax/upyOS#9]
```
/bin $: wifi phy_mode
Error executing wifi
Traceback (most recent call last):
  File "/lib/proc.py", line 51, in run
  File "wifi.py", line 138, in __main__
AttributeError: 'module' object has no attribute 'phy_mode'
```

**Comment by rbenrax** [comment]
Thanks, Sivansh, for your work.

That's an implementation limitation. Apparently, the RPI W2's Wi-Fi chip is connected via SPI, and the driver is limited, unlike ESP, which is on the same silicon. The only thing we can do is remove the feature for this platform. CircuitPython seems to have a better implementation.

One question: do you finally have Wi-Fi working on the RPI W2?

**Comment by sivansh11** [comment]
Just to clarify, since I am unaware of the naming schemes, if by RPI W2 you mean pico w, then yes, I have wifi working!
Yeah I am aware that there are some differences between binaries of micropython for each boards, tho I am unsure where I can look these up.

**Comment by rbenrax** [comment]
Fixed,

I've made quite a few changes, including some messages in the Wi-Fi command. Update the repository and let me know. Thanks.

**Comment by sivansh11** [comment]
@rbenrax I am still getting similar error, take a look at https://github.com/rbenrax/upyOS/commit/a9b142fa07fb05bc70952475bcf3422b6f2da138#commitcomment-168112870

```
/ $: wifi phy_mode
Error executing wifi
Traceback (most recent call last):
  File "/lib/proc.py", line 51, in run
  File "/bin/wifi.py", line 153, in __main__
AttributeError: 'module' object has no attribute 'phy_mode'
```

I have no idea why this is occurring since the hardcoded check should have caught this, anyways my suggestion still stands, rather than checking for hardcoded name, check if phy_mode object exits, simpler and more portable

**Comment by rbenrax** [comment]
Have you updated everything, or at least the lib directory?

**Comment by sivansh11** [comment]
yes, pretty sure I have updated everything, 
git pull for latest changes
followed by
 
mpremote fs -v cp main.py :main.py
mpremote fs -r -v cp bin etc lib libx opt tmp www :

**Comment by rbenrax** [comment]
/ $: lshw
SystemID: E462146703121C28
Platform: rp2
Board: Raspberry Pi Pico with RP2040
upyOS-rp2 : 0.9.1
MicroPython: 1.26.1
Firmware: v1.26.1 on 2025-09-11 (GNU 14.2.0 MinSizeRel)
CPU Speed: 125.0MHz
/ $: wifi phy_mode
Networking is not implemented on this platform
Verify that your board has Wi-Fi, that it is loading the appropriate .board 
configuration file in /etc/init.sh, and that Wi-Fi support is enabled in it.
Name error executing wifi
Try enabling debug
/ $: 

My RP2 doesn't have WiFi.

**Comment by rbenrax** [comment]
Can you send me the output of the lshw command?

**Comment by sivansh11** [comment]
do you have a pico or a pico w, there is a difference

**Comment by sivansh11** [comment]
/ $: lshw
SystemID: E66428C51F468C22
Platform: rp2
Board: Raspberry Pi Pico W with RP2040
upyOS-rp2 : 0.9.1
MicroPython: 1.26.1
Firmware: v1.26.1 on 2025-09-11 (GNU 14.2.0 MinSizeRel)
CPU Speed: 125.0MHz

**Comment by rbenrax** [comment]
Try now

**Comment by rbenrax** [comment]
Explanation:
/ $: > import uos
/ $: < uos.uname()
(sysname='rp2', nodename='rp2', release='1.26.1', version='v1.26.1 on 2025-09-11 (GNU 14.2.0 MinSizeRel)', machine='Raspberry Pi Pico with RP2040')
/ $: < uos.uname()[4]
Raspberry Pi Pico with RP2040
/ $: 

For other issues play with:
/ $: > sdata.debug=True
/ $: > sdata.debug=False

**Comment by sivansh11** [comment]
its working now!
